### ISSUE TITLE
Weird Repo

### ISSUE THREAD

**Issue by Pittini** [Mazze2000/ioBroker.awtrix#1]
What is this Repo? Is it something with "Luftdaten" as the readme says or is it a Awtrix iobroker Adapter (as package json says)? Weird!

**Comment by Mazze2000** [comment]
Hey Pittini,
i starts with the repo from Matthias Kleine (Luftdaten) to develop a awtrix adapter for ioBroker.
But I'm not sure if a awtrix adapter is really necessary...
Matze

**Comment by Pittini** [comment]
Ok, tnx.
I'm not finished atm, but maybe you wanna look at this: https://github.com/Pittini/iobroker-awtrix
